// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hotel.proto

package stubs;

public interface CreateReservationResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CreateReservationResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.Reservation reservation = 1;</code>
   * @return Whether the reservation field is set.
   */
  boolean hasReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   * @return The reservation.
   */
  stubs.Reservation getReservation();
  /**
   * <code>.Reservation reservation = 1;</code>
   */
  stubs.ReservationOrBuilder getReservationOrBuilder();
}
